version: '3.8'

services:
  websocket-server:
    build: .
    ports:
      - "6001:6001"
    environment:
      - NODE_ENV=production
      - WEBSOCKET_PORT=6001
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:8000}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:6001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
